-- MySQL Script generated by MySQL Workbench
-- Fri Feb 10 18:22:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Gestick`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gestick` (
  `idGestick` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Contrasenna` VARCHAR(45) NOT NULL,
  `Gestickcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idGestick`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `idAdmin` INT NOT NULL,
  `AdNombre` VARCHAR(45) NOT NULL,
  `AdAppat` VARCHAR(45) NOT NULL,
  `AdApmat` VARCHAR(45) NOT NULL,
  `AdContrasenna` VARCHAR(45) NOT NULL,
  `Gestick_idGestick` INT NOT NULL,
  PRIMARY KEY (`idAdmin`, `Gestick_idGestick`),
  UNIQUE INDEX `idAdmin_UNIQUE` (`idAdmin` ASC) VISIBLE,
  INDEX `fk_Admin_Gestick1_idx` (`Gestick_idGestick` ASC) VISIBLE,
  CONSTRAINT `fk_Admin_Gestick1`
    FOREIGN KEY (`Gestick_idGestick`)
    REFERENCES `mydb`.`Gestick` (`idGestick`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Marca` (
  `idMarca` INT NOT NULL,
  `MarNombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `CatNombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Productos` (
  `idProductos` INT NOT NULL,
  `PrNombre` VARCHAR(45) NOT NULL,
  `PrPrecio` VARCHAR(45) NOT NULL,
  `PrExistencias` INT(100) NOT NULL,
  `PrDescripcion` VARCHAR(45) NULL,
  `Admin_idAdmin` INT NOT NULL,
  `Marca_idMarca` INT NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idProductos`, `Admin_idAdmin`, `Marca_idMarca`, `Categoria_idCategoria`),
  UNIQUE INDEX `idProductos_UNIQUE` (`idProductos` ASC) VISIBLE,
  INDEX `fk_Productos_Admin_idx` (`Admin_idAdmin` ASC) VISIBLE,
  INDEX `fk_Productos_Marca1_idx` (`Marca_idMarca` ASC) VISIBLE,
  INDEX `fk_Productos_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_Admin`
    FOREIGN KEY (`Admin_idAdmin`)
    REFERENCES `mydb`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `mydb`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Imagen Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Imagen Producto` (
  `idImagen Producto` INT NOT NULL,
  `ImProURL` LONGTEXT NOT NULL,
  `tipoImagenPro` VARCHAR(45) NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  `Productos_Admin_idAdmin` INT NOT NULL,
  PRIMARY KEY (`idImagen Producto`, `Productos_idProductos`, `Productos_Admin_idAdmin`),
  INDEX `fk_Imagen Producto_Productos1_idx` (`Productos_idProductos` ASC, `Productos_Admin_idAdmin` ASC) VISIBLE,
  UNIQUE INDEX `idImagen Producto_UNIQUE` (`idImagen Producto` ASC) VISIBLE,
  CONSTRAINT `fk_Imagen Producto_Productos1`
    FOREIGN KEY (`Productos_idProductos` , `Productos_Admin_idAdmin`)
    REFERENCES `mydb`.`Productos` (`idProductos` , `Admin_idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VentasPro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VentasPro` (
  `idVentasPro` INT NOT NULL,
  `CantidadVendida` VARCHAR(45) NOT NULL,
  `DineroPro` VARCHAR(45) NOT NULL,
  `Fecha` DATETIME(5) NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  `Productos_Admin_idAdmin` INT NOT NULL,
  PRIMARY KEY (`idVentasPro`, `Productos_idProductos`, `Productos_Admin_idAdmin`),
  UNIQUE INDEX `idVentasPro_UNIQUE` (`idVentasPro` ASC) VISIBLE,
  INDEX `fk_VentasPro_Productos1_idx` (`Productos_idProductos` ASC, `Productos_Admin_idAdmin` ASC) VISIBLE,
  CONSTRAINT `fk_VentasPro_Productos1`
    FOREIGN KEY (`Productos_idProductos` , `Productos_Admin_idAdmin`)
    REFERENCES `mydb`.`Productos` (`idProductos` , `Admin_idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `idEmpleado` INT NOT NULL,
  `EmNombre` VARCHAR(45) NOT NULL,
  `EmApat` VARCHAR(45) NOT NULL,
  `EmAmat` VARCHAR(45) NOT NULL,
  `EmContrasenna` VARCHAR(50) NOT NULL,
  `Admin_idAdmin` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`, `Admin_idAdmin`),
  INDEX `fk_Empleado_Admin1_idx` (`Admin_idAdmin` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Admin1`
    FOREIGN KEY (`Admin_idAdmin`)
    REFERENCES `mydb`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
