-- MySQL Script generated by MySQL Workbench
-- Fri Apr 21 11:39:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Gestick`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gestick` (
  `idGestick` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Contrasenna` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGestick`),
  UNIQUE INDEX `idGestick_UNIQUE` (`idGestick` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `AdNombre` VARCHAR(45) NOT NULL,
  `AdAppat` VARCHAR(45) NOT NULL,
  `AdApmat` VARCHAR(45) NOT NULL,
  `AdContrasenna` VARCHAR(45) NOT NULL,
  `Gestick_idGestick` INT NOT NULL,
  `Aactivo` TINYINT NOT NULL,
  `AdEmail` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idAdmin`),
  UNIQUE INDEX `idAdmin_UNIQUE` (`idAdmin` ASC) VISIBLE,
  INDEX `fk_Admin_Gestick1_idx` (`Gestick_idGestick` ASC) VISIBLE,
  UNIQUE INDEX `AdEmail_UNIQUE` (`AdEmail` ASC) VISIBLE,
  CONSTRAINT `fk_Admin_Gestick1`
    FOREIGN KEY (`Gestick_idGestick`)
    REFERENCES `mydb`.`Gestick` (`idGestick`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Marca` (
  `idMarca` INT NOT NULL AUTO_INCREMENT,
  `MarNombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `CatNombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Productos` (
  `idProductos` INT NOT NULL AUTO_INCREMENT,
  `PrNombre` VARCHAR(45) NOT NULL,
  `PrPrecio` VARCHAR(45) NOT NULL,
  `PrExistencias` INT(100) NOT NULL,
  `PrDescripcion` VARCHAR(100) NULL,
  `Admin_idAdmin` INT NOT NULL,
  `Marca_idMarca` INT NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  `Pcodigo` INT NOT NULL,
  `PrURLimg` VARCHAR(600) NOT NULL DEFAULT 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.importadoraespinoza.com%2Ffunda-para-empaque-al-vacio-19-micras-no-texturizada-100-unidades-al-vacio-20-26cm&psig=AOvVaw0dUPufBHpPKXl1Co7PLpr1&ust=1682020525393000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCJDLu_Hctv4CFQAAAAAdAAAAABAE',
  PRIMARY KEY (`idProductos`),
  UNIQUE INDEX `idProductos_UNIQUE` (`idProductos` ASC) VISIBLE,
  INDEX `fk_Productos_Admin_idx` (`Admin_idAdmin` ASC) VISIBLE,
  INDEX `fk_Productos_Marca1_idx` (`Marca_idMarca` ASC) VISIBLE,
  INDEX `fk_Productos_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_Admin`
    FOREIGN KEY (`Admin_idAdmin`)
    REFERENCES `mydb`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `mydb`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `EmNombre` VARCHAR(45) NOT NULL,
  `EmApat` VARCHAR(45) NOT NULL,
  `EmAmat` VARCHAR(45) NOT NULL,
  `EmContrasenna` VARCHAR(150) NOT NULL,
  `EmDireccion1` VARCHAR(500) NULL,
  `EmDireccion2` VARCHAR(500) NULL,
  `Admin_idAdmin` INT NOT NULL,
  `Admin_Gestick_idGestick` INT NOT NULL,
  `EmURLimg` VARCHAR(600) NULL DEFAULT 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fflejedecosas.com%2Fcomo-crear-un-usuario-en-google-chrome-seguro-te-servira%2F&psig=AOvVaw1bHODCRENdLfwzukb-Ga5a&ust=1682019626152000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCJiJg8XZtv4CFQAAAAAdAAAAABBM',
  PRIMARY KEY (`idEmpleado`),
  INDEX `fk_Empleado_Admin1_idx` (`Admin_idAdmin` ASC, `Admin_Gestick_idGestick` ASC) VISIBLE,
  UNIQUE INDEX `idEmpleado_UNIQUE` (`idEmpleado` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Admin1`
    FOREIGN KEY (`Admin_idAdmin` , `Admin_Gestick_idGestick`)
    REFERENCES `mydb`.`Admin` (`idAdmin` , `Gestick_idGestick`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carrito` (
  `idCarrito` INT NOT NULL AUTO_INCREMENT,
  `CarFecha` DATE NOT NULL,
  `Total` FLOAT NOT NULL,
  `idEmpleadoC` INT NOT NULL,
  PRIMARY KEY (`idCarrito`),
  UNIQUE INDEX `idCarrito_UNIQUE` (`idCarrito` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productos_has_Carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Productos_has_Carrito` (
  `Productos_idProductos` INT NOT NULL,
  `Productos_Admin_idAdmin` INT NOT NULL,
  `Productos_Marca_idMarca` INT NOT NULL,
  `Productos_Categoria_idCategoria` INT NOT NULL,
  `Carrito_idCarrito` INT NOT NULL,
  `ProVendidos` INT NOT NULL,
  PRIMARY KEY (`Productos_idProductos`, `Productos_Admin_idAdmin`, `Productos_Marca_idMarca`, `Productos_Categoria_idCategoria`, `Carrito_idCarrito`),
  INDEX `fk_Productos_has_Carrito_Carrito1_idx` (`Carrito_idCarrito` ASC) VISIBLE,
  INDEX `fk_Productos_has_Carrito_Productos1_idx` (`Productos_idProductos` ASC, `Productos_Admin_idAdmin` ASC, `Productos_Marca_idMarca` ASC, `Productos_Categoria_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_has_Carrito_Productos1`
    FOREIGN KEY (`Productos_idProductos` , `Productos_Admin_idAdmin` , `Productos_Marca_idMarca` , `Productos_Categoria_idCategoria`)
    REFERENCES `mydb`.`Productos` (`idProductos` , `Admin_idAdmin` , `Marca_idMarca` , `Categoria_idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_has_Carrito_Carrito1`
    FOREIGN KEY (`Carrito_idCarrito`)
    REFERENCES `mydb`.`Carrito` (`idCarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
